version: '3'

services:
  app:
    restart: always
    
    build: app/.
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./data:/app/data
    environment:
      - DATA_FOLDER_PATH=${DATA_FOLDER_PATH}
      - SECRET_API_KEY=${SECRET_API_KEY}